### ISSUE TITLE
视频文件大于500M，就无法转换

### ISSUE THREAD

**Issue by a285990** [joisun/ffmpeg-convertor#1]
视频文件大于500M，就无法转换，各种报错乱码！多1M都不行

**Comment by joisun** [comment]
> 视频文件大于500M，就无法转换，各种报错乱码！多1M都不行

可能不是文件大小引起的， 之前的输出默认文件名会和输入保持一致，现在默认为转换输出添加了时间后缀防止重复，可以再次尝试看看。

**Comment by a285990** [comment]
感谢您还在维护这个项目,支持您的开源精神!

很遗憾您新修改的2个文件,我已经替换了,可惜问题依然存在,我在火狐和谷歌浏览器都试了,如果视频大于500M 就无法转换了,我同时测试了多段大于500M的视频都无法转换,小于500M的就可以! 

500M以上的视频 ,点击转换,会下载一个 0B 的视频文件,并未成功转换!

**Comment by joisun** [comment]
> 感谢您还在维护这个项目,支持您的开源精神!
> 
> 很遗憾您新修改的2个文件,我已经替换了,可惜问题依然存在,我在火狐和谷歌浏览器都试了,如果视频大于500M 就无法转换了,我同时测试了多段大于500M的视频都无法转换,小于500M的就可以!
> 
> 500M以上的视频 ,点击转换,会下载一个 0B 的视频文件,并未成功转换!

我这边测试都是正常的，你这边详细的报错信息可以提供一下。  
另外，转换视频会临时缓存在内存中，所以有一种少见的情况可能是你内存不够。
